services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./formapp:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

  backend:
    build: ./formback
    container_name: form_backend
    ports:
      - "5000:5000"
    volumes:
      - ./formback/submissions.json:/app/submissions.json

