services:
  frontend:
    build:
      context: ./formapp   # folder where frontend Dockerfile is
    container_name: frontend
    restart: always
    ports:
      - "8000:8000"

  backend:
    build:
      context: ./formback   # folder where backend Dockerfile is
    container_name: backend
    restart: always
    ports:
      - "5000:5000"
  
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"   # host port 8080 → container port 80
    depends_on:
      - frontend
      - backend

    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

    restart: always
